---
- hosts: prod
  user: root
  sudo: no
  tags: init
  vars:
  - ssh_user: $ENV(USER)

  tasks:
  - name: INIT | There's an Admin system group
    group: name=admins system=yes state=present
    tags: init

  - name: INIT | The current ssh user has an admin account
    user: name=$ssh_user state=present shell=/bin/bash groups=admins
    tags: init

  - name: INIT | Current user's ssh public key is authorized
    authorized_key: user=$ssh_user key="$FILE(~/.ssh/id_rsa.pub)"
    tags: init

  - name: INIT | Install sudoers file for admin accounts
    lineinfile: "dest=/etc/sudoers.d/admins state=present create=yes regexp='^%admins' line='%admins ALL=(ALL:ALL) NOPASSWD: SETENV: ALL' owner=root group=root mode=0440"
    tags: init

  - name: INIT | nginx is installed
    apt: pkg=nginx state=present
    tags:
       - init
       - install